# Introduction Session.

This is a demo text. This is a `demo` text. This is a **demo** text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a *demo* text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. This is a demo text. 

### Second Heading

In [3]:
print("Hello World")

Hello World


In [22]:
a = 5
b = 4.5
c = 'Diwash'

In [21]:
print(c)
print(b, c)
print(a + b)

Diwash
4.5 Diwash
9.5


In [25]:
my_variable = 200
my_variable

200

In [38]:
my_var2 = 30
_myvar3 = 50
print(my_var2)
_myvar3

30


50

In [31]:
my_var2, _myvar3

(30, 50)

In [33]:
# The following code won't work
# 9var = 45

SyntaxError: invalid decimal literal (1862106279.py, line 2)

In [43]:
'''
This is a multiline comment
This is a multiline comment
This is a multiline comment
'''
print( 3 * 5)
print( 4 * 10.5)
print( 'text' * 5)

15
42.0
texttexttexttexttext


In [44]:
# %pwd

'C:\\Users\\diwas\\OneDrive\\Desktop\\python\\Class'

In [56]:
country = "Nepal"
city = "Kathmandu"
area = 147181
language = "Nepali"
game = 'volleyball'

In [58]:
country, game, area

('Nepal', 'volleyball', 147181)

In [59]:
print(country, city, area, language)

Nepal Kathmandu 147181 Nepali


In [62]:
print(country + ' ' + city + ' ' + language)

Nepal Kathmandu Nepali


In [68]:
print('The area of Nepal is area. country city language')

The area of Nepal is area. country city language


In [67]:
print(f'The area of {country} is {area}.')

The area of Nepal is 147181.


In [73]:
print('The area of Nepal is', area)
print('The area of Nepal is' + ' ' + str(area))

The area of Nepal is 147181
The area of Nepal is 147181


In [74]:
# create two variables called firstname, lastname with values
# create another variable that concatenates the two variables
# print the concatenated value

In [76]:
firstname = "John"
lastname = "Doe"
fullname = firstname + " " + lastname
print(fullname)

John Doe


In [13]:
# Get input from the user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Calculate the product
product = num1 * num2

# Display the result
print(f"The product of {num1} and {num2} is {product}")

Enter the first number:  40
Enter the second number:  50


The product of 40.0 and 50.0 is 2000.0


In [11]:
x = 4
print(x * 5)

20


In [12]:
print(str(x) * 5)

44444


In [14]:
# Taking user input
num = int(input("Enter a number: "))

# Check if the number is odd or even
if (num % 2) == 0:
    print(f"{num} is Even")
else:
    print(f"{num} is Odd")

Enter a number:  5


5 is Odd


In [16]:
5 / 2
5 % 2

1

In [20]:
# Access individual characters in a string
message = "Hello, world!"
print(f"First character: {message[-5:-1]}")

First character: orld


In [21]:
my_list = [1, 2, 10, 30, 3, 2.4]
my_list2 = ['code', 'rice', 'zion', 'hello']

my_list.sort()
my_list2.sort()

print(my_list) # prints [1, 2, 2.4, 3, 10, 30]
print(my_list2) # prints ['code', 'hello', 'rice', 'zion']


[1, 2, 2.4, 3, 10, 30]
['code', 'hello', 'rice', 'zion']


<img src='./images/python operator precedence.png'>

In [5]:
# Case Sensitivity in Python
myvar = 45
Myvar = 'Hello World!'
MYVAR = 180

In [3]:
print(myvar, Myvar, MYVAR)

45 Hello World! 180


In [18]:
2 ** 5

32

In [20]:
x = 5
-x

-5

In [21]:
var1 = 'Diwash Sapkota'

In [27]:
var1[1:4]
var1[-1]

'a'

In [31]:
var1.upper()
var1.title()

'Diwash Sapkota'

In [32]:
var1.lower()

'diwash sapkota'

In [55]:
var4 = 'diwash sapkota'
var4.capitalize()
var4.title()

'Diwash Sapkota'

In [41]:
var2 = 'Today is Tuesday'

In [35]:
var2.lstrip()

'Today is Wednesday   '

In [39]:
var2.strip()

'Today  is Wednesday'

In [42]:
var3 = 'Today is Tuesday'

In [50]:
var3.replace('Tuesday', 'Wednesday')

'Today is Wednesday'

In [52]:
len(var3)

18

In [18]:
x = (4 - 20)

In [19]:
x

-16

In [20]:
abs(x)

16

In [21]:
list1 = ['Nepal', 'India', 'Bhutan', 'Bangladesh', 'Afghanistan', 'China']

for country in list1:
    if len(country) <= 5:
        print(country)

Nepal
India
China


In [23]:
# i = 5

# for j in range(1, 11):
#     print(i * j)


list4 = [5, 10, 15, 20, 25]
total = 0

for item in list4:
    total = total + item
print(total)

75


In [19]:
mystring = 'Hi, Diwash Sapkota here!'
mystring[1:10:2]

'i iah'

In [29]:
List = [['Geeks', 'For'], ['Geeks']]
print("\nMulti-Dimensional List: ")
# List[0].insert(0, "all")
print(List)


Multi-Dimensional List: 
[['Geeks', 'For'], ['Geeks']]


In [23]:
List[0][1]

'For'

In [24]:
List[0].append('all')

In [17]:
List

NameError: name 'List' is not defined

## Class 3 Assignments

In [6]:
# 1. Count all letters, digits, and special symbols from a given string (eg: Pr1X@%@24Ac&d3mY)
input_string = 'Pr1X@%@24Ac&d3mY'

# Initialize counters
letters = digits = symbols = 0

# Iterate through each character in the string
for char in input_string:
    if char.isalpha():
        letters = (letters + 1)
        print(char, letters)
    elif char.isdigit():
        digits = (digits + 1)
        print(char, digits)
    else:
        symbols = (symbols + 1)
        print(char, symbols)

# Print the results
print("Letters =", letters)
print("Digits =", digits)
print("Special symbols =", symbols)

P 1
r 2
1 1
X 3
@ 1
% 2
@ 3
2 2
4 3
A 4
c 5
& 4
d 6
3 4
m 7
Y 8
Letters = 8
Digits = 4
Special symbols = 4


In [2]:
x = 'Diwash'
x[0]

'D'

In [11]:
# 2. Write a program to find all occurrences of the word “is” in a given string ignoring the case. 

input_text = "This is a sample sentence. IS it working? Yes, it is !"

# Convert the entire text to lowercase for case-insensitive comparison
text_lower = input_text.lower()
print(text_lower)

# Split the text into words
words = text_lower.split()
print(words)

# Initialize a counter for occurrences of "is"
is_count = 0
find_word = 'is'

# Check each word
for word in words:
    if word == find_word:
        is_count += 1

print(f"Occurrences of 'is': {is_count}")

this is a sample sentence. is it working? yes, it is !
['this', 'is', 'a', 'sample', 'sentence.', 'is', 'it', 'working?', 'yes,', 'it', 'is', '!']
Occurrences of 'is': 3


In [12]:
# 3. Given a list of numbers. write a program to turn every item of a list into its square.
my_list = [1, 2, 3, 4, 5]
squared_list = []

for number in my_list:
    squared_list.append(number ** 2)
print(squared_list)

[1, 4, 9, 16, 25]


In [15]:
'''
4. You have given a Python list. Write a program to find value 20 in the list, 
and if it is present, replace it with 200. Only update the first occurrence of an item.
'''
my_list = [5, 10, 15, 20, 25, 50, 20]

# Find the index of the first occurrence of 20
if 20 in my_list:
    i = my_list.index(20)
    print(i, my_list[i])
    my_list[i] = 200

print(my_list)


3 20
[5, 10, 15, 200, 25, 50, 20]


## Class 4

In [6]:
# Check if the number entered by the user is prime or not

def is_prime(number):
    """
    Checks if a given number is prime.
    """
    if number <= 1:
        return False  # Numbers less than or equal to 1 are not prime

    # Check for divisors from 2 to the square root of the number
    for divisor in range(2, int(number**0.5) + 1):
        if number % divisor == 0:
            return False  # Found a divisor, so it's not prime

    return True  # No divisors found, it's prime

# Example usage:
user_input = int(input("Enter a positive integer: "))
if is_prime(user_input):
    print(f"{user_input} is a prime number.")
else:
    print(f"{user_input} is not a prime number.")

Enter a positive integer:  7


7 is a prime number.


In [12]:
# Check whether the input string is palindrome or not
def is_palindrome(s):
    """
    Checks if a given string is a palindrome.
    """
    # Remove spaces and convert to lowercase
    s = s.replace(" ", "").lower()
    a = (s == s[::-1])
    print(a)
    # Compare the original string with its reverse
    return a

# Example usage:
user_input = input("Enter a string: ")
if is_palindrome(user_input):
    print(f"'{user_input}' is a palindrome.")
else:
    print(f"'{user_input}' is not a palindrome.")

# Eg: No lemon, no melon

Enter a string:  No lemon no melon


True
'No lemon no melon' is a palindrome.


In [10]:
a = 'Diwash'
a[::-1]

'hsawiD'

In [14]:
# Use a loop to display elements from a given list present at odd index positions 
my_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
# stat from index 1 with step 2( means 1, 3, 5, an so on)
for i in my_list[1::2]:
    print(i)
    print()

20

40

60

80

100



In [2]:
# Extract all odd numbers from arr
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]
#> array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [4]:
# Replace all odd numbers in arr with -1
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
#Remove some items from dictionary
sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"
}
print('Before deleting age key', sample_dict)

# del sample_dict['age']
# print('After deleting age key', sample_dict)
# sample_dict.pop('city')
# Keys to remove
keys = ["name", "salary"]

for k in keys:
    sample_dict.pop(k)

print(sample_dict)

Before deleting age key {'name': 'Kelly', 'age': 25, 'salary': 8000, 'city': 'New york'}
{'age': 25, 'city': 'New york'}


In [4]:
students = {
    'sid1' : {
        'name' : 'John',
        'class' : 9,
        'address' : 'Kathmandu'
    },
    
    'sid2' : {
        'name' : 'Ramesh',
        'class' : 10,
        'address' : 'Biratnagar'
    }
}

# students
students['sid1']
students['sid1']['name'] = 'Raju'
students['sid3'] = {'name' : 'Rakesh', 'class' : 7, 'address' : 'Dharan'}
students

{'sid1': {'name': 'Raju', 'class': 9, 'address': 'Kathmandu'},
 'sid2': {'name': 'Ramesh', 'class': 10, 'address': 'Biratnagar'},
 'sid3': {'name': 'Rakesh', 'class': 7, 'address': 'Dharan'}}

In [15]:
food_data = {
    'fruits': 
    {
        'apple': {
            'color': 'red',
            'taste': 'sweet',
            'vitamins': ['A', 'C'],
        },
        'banana': {
            'color': 'yellow',
            'taste': 'sweet',
            'vitamins': ['B6', 'C'],
        },
    },
    'vegetables': {
        'carrot': {
            'color': 'orange',
            'taste': 'crunchy',
            'vitamins': ['A', 'K'],
        },
        'spinach': {
            'color': 'black',
            'taste': 'nutty',
            'vitamins': ['A', 'C', 'K'],
        },
    }
}

In [16]:
food_data

{'fruits': {'apple': {'color': 'red',
   'taste': 'sweet',
   'vitamins': ['A', 'C']},
  'banana': {'color': 'yellow', 'taste': 'sweet', 'vitamins': ['B6', 'C']}},
 'vegetables': {'carrot': {'color': 'orange',
   'taste': 'crunchy',
   'vitamins': ['A', 'K']},
  'spinach': {'color': 'black',
   'taste': 'nutty',
   'vitamins': ['A', 'C', 'K']}}}

In [64]:
food_data['vegetables']['spinach']['color'] = 'green'

In [65]:
food_data['vegetables']['spinach']['color']

'green'

In [12]:
sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"
}

# keys and values

for details in sample_dict.keys():
    print(details)
print()

for val in sample_dict.values():
    print(val)

print()
for i, j in sample_dict.items():
    print(i, j)

name
age
salary
city

Kelly
25
8000
New york

name Kelly
age 25
salary 8000
city New york
